const affirmations = [
    { quote: "I am capable of achieving my goals." },
    { quote: "I am deserving of love and respect." },
    { quote: "I am grateful for the opportunities life brings me." },
    { quote: "I trust in my ability to make the right decisions." },
    { quote: "I am worthy of success and happiness." },
    { quote: "I attract positivity into my life." },
    { quote: "I am becoming the best version of myself." },
    { quote: "I am in control of my thoughts and emotions." },
    { quote: "I choose happiness and abundance in my life." },
    { quote: "I radiate confidence and self-assurance." },
    { quote: "I embrace change and see it as an opportunity for growth." },
    { quote: "I am capable of overcoming any challenges that come my way." },
    { quote: "I am surrounded by love and support." },
    { quote: "I am a magnet for success and prosperity." },
    { quote: "I am resilient and can bounce back from setbacks." },
    { quote: "I am creating a life filled with joy and fulfillment." },
    { quote: "I am worthy of all the good things that come into my life." },
    { quote: "I am at peace with who I am." },
    { quote: "I am open to receiving abundance in all areas of my life." },
    { quote: "I believe in my ability to achieve my dreams." },
    { quote: "I am capable, strong, and resilient." },
    { quote: "I am constantly growing and evolving." },
    { quote: "I am surrounded by positivity and abundance." },
    { quote: "I am confident in my abilities to succeed." },
    { quote: "I am worthy of love and respect from others." },
    { quote: "I am grateful for the gift of today." },
    { quote: "I am blessed with limitless potential." },
    { quote: "I am a magnet for miracles." },
    { quote: "I am worthy of all the good things that come into my life." },
    { quote: "I am at peace with who I am." },
    { quote: "I am open to receiving abundance in all areas of my life." },
    { quote: "I believe in my ability to achieve my dreams." },
    { quote: "I am capable, strong, and resilient." },
    { quote: "I am constantly growing and evolving." },
    { quote: "I am surrounded by positivity and abundance." },
    { quote: "I am confident in my abilities to succeed." },
    { quote: "I am worthy of love and respect from others." },
    { quote: "I am grateful for the gift of today." },
    { quote: "I am blessed with limitless potential." },
    { quote: "I am a magnet for miracles." },
    { quote: "I am committed to my goals and dreams." },
    { quote: "I am worthy of all the success that comes my way." },
    { quote: "I am loved, supported, and appreciated." },
    { quote: "I am in alignment with my true purpose." },
    { quote: "I am capable of overcoming any obstacle." },
    { quote: "I am grateful for the lessons that challenges bring." },
    { quote: "I am worthy of happiness and fulfillment." },
    { quote: "I am surrounded by abundance in all areas of my life." },
    { quote: "I am confident in my ability to create the life I desire." }
];

export default affirmations; 