version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1
  node: circleci/node@5.0.3

workflows:
  build:
    jobs:
      - start_server:
          context: netlify
      - build_and_test:
          context: netlify
          requires:
            - start_server
      - deploy_to_netlify:
          context: netlify
          requires:
            - build_and_test
      - cypress/run: # Run the cypress/run job from the cypress orb
          cypress-command: npx cypress run --headless # Run the cypress run command in headless mode
          start-command: cypress run

jobs:
  start_server:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Start Development Server
          command: npm start
          background: true # Run the server in the background

  build_and_test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install 

  deploy_to_netlify:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Deploy to Netlify
          command: |
            curl -X POST -d '{}' -H 'Content-Type: application/json' -H 'Authorization: Bearer $NETLIFY_AUTH_TOKEN' https://api.netlify.com/build_hooks/$NETLIFY_BUILD_HOOK_ID
