version: 2.1

orbs:
  cypress: cypress-io/cypress@3.1.1

workflows:
  build:
    jobs:
      - build_and_test:
          context: netlify # Set up the context for environment variables
          requires:
            - start_server # Wait for the server to start before running Cypress tests
      - deploy_to_netlify:
          context: netlify # Set up the context for environment variables
          requires:
            - build_and_test # Wait for tests to pass before deploying to Netlify

jobs:
  start_server:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Start Development Server
          command: npm start
          background: true # Run the server in the background

  build_and_test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Cypress Tests
          command: npm run cypress:run -- --headless --browser chrome # Run Cypress tests in headless mode

  deploy_to_netlify:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Deploy to Netlify
          command: |
            curl -X POST -d '{}' -H 'Content-Type: application/json' -H 'Authorization: Bearer $NETLIFY_AUTH_TOKEN' https://api.netlify.com/build_hooks/$NETLIFY_BUILD_HOOK_ID
          environment:
            NETLIFY_AUTH_TOKEN: NETLIFY_AUTH_TOKEN
            NETLIFY_BUILD_HOOK_ID: YOUR_NETLIFY_BUILD_HOOK_ID
