describe('Login page', () => {
  beforeEach(() => {
    cy.visit('http://127.0.0.1:5173/')
  })
  it('should show the user the login form', () => {
    cy.get('h1').contains('Brain Food')
    cy.get('form').should('exist')
    cy.get('label').first().contains('Email:')
    cy.get('label').last().contains('Password:')
    cy.get('button').first().contains('Sign in')
    // cy.get('button').click()
    cy.get('h2').contains('Don\'t have an account?')
    cy.get('.MuiButtonBase-root').contains('Create one').click({force: true})
    cy.get('.MuiBox-root').should('exist')
    cy.get('h2').contains('Create a Brain Food Account')
    cy.get('h3').contains('Let\'s get cookin\'!')
    cy.get('form').should('exist')
    cy.get('#name').should('have.attr', 'placeholder', 'Enter your name here')
    // cy.get('button).click()
    cy.get('.exit').click()
  })
})